<h1>Here you can find our contacts</h1>
<table><tr>
    <th>Photo</th>
    <th>Person</th>
    <th>How to contact them</th>
</tr>
<tr>
    <td><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=jurica-koletic-7YVZYZeITc8-unsplash.jpg&w=640" class="avatar" /></td>
    <td>John Doe</td>
    <td>Mail him: <a href="mailto:john.doe@example.com">john.doe@example.com</a></td>
</tr>
<tr>
    <td><img src="https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=slav-romanov-BrEAp01_m5w-unsplash.jpg&w=640" class="avatar" /></td>
    <td>Jane Doe</td>
    <td>Mail her: <a href="mailto:jane.doe@example.com">jane.doe@example.com</a></td>
</tr>
</table>
